### ISSUE TITLE
Installation on Other Distributions?

### ISSUE THREAD

**Issue by MrGamerChad** [dylanaraps/openbox-patched#13]
I noticed that in terms of installation instructions, theres at most the AUR package, but that only works on Arch and its derivatives, so anyone else seems to be sort-of left out in terms of using this patchset. For example, I attempted the build myself on an OpenSUSE install I was testing and it only lead to the normal Openbox being done through using configure and make on the cloned repo. Is there anyway to apply the patches manually? Sorry if this is the improper area to post this, I'm not too knowledgable on what signifies use of an Issue post, so apologies.

**Comment by novel** [comment]
I think you can download patches and apply using `patch -p1 < path_to.patch` on top of the openbox sources. Patches are in the top level directory of this repo.

FWIW, I've included these patches into the FreeBSD openbox port some time ago: https://docs.freebsd.org/cgi/getmsg.cgi?fetch=80664+0+/usr/local/www/mailindex/archive/2018/svn-ports-all/20180128.svn-ports-all

**Comment by MrGamerChad** [comment]
@novel Yup, that worked. Thanks for the help! It seems I should have just tried running the patch commands from the PKGBUILD in the openbox source folder in the first place. It would be nice if there were some instructions so that others using other distros with no real experience of the patch command can use these patches too, but hey, whatever works. I'm closing this issue as there seems to be no further need for it.

**Comment by predragnikolic** [comment]
Where is openbox source folder located? I can't find it. 
I installed it with `sudo apt-get install openbox`.
