### ISSUE TITLE
Error with the PGP signatures

### ISSUE THREAD

**Issue by jonathashenriques** [dylanaraps/openbox-patched#3]
Can't install it via AUR

**Comment by dylanaraps** [comment]
What's the exact error you're getting from `makepkg`?

**Comment by jonathashenriques** [comment]
`One or more PGP signatures could not be verfied!`

**Comment by dylanaraps** [comment]
It looks like one of the Openbox PGP keys has expired, I based the `PKGBUILD` off of the official Arch package for Openbox so I'm not really sure about what to do here.

We might have to skip the PGP check if there isn't a valid key we can use.

**Comment by jonathashenriques** [comment]
All right, skip tthe PGP check worked

**Comment by jonathashenriques** [comment]
Dylan, is it possible to get the rounded corners working with dunst ?

**Comment by dylanaraps** [comment]
I don't think so since `dunst`'s notifications arent "windows" to the window manager. This might be possible on dunst's end (*It would work in any WM/DE*). It might be worth opening a feature request on their GitHub repo.

**Comment by dylanaraps** [comment]
I've removed the PGP key from the PKGBUILD.
