### ISSUE TITLE
Corners aren't rendered when client requests a resize

### ISSUE THREAD

**Issue by ghost** [dylanaraps/openbox-patched#5]
Hope I worded this correctly; if Chrome (for example) has "Use system titlebar and borders" turned off, I'm assuming that clicking the maximize button actually makes the request from the client side... And in this case the corners won't be rendered until some other action is taken on the window. 

Here's what I mean by illustration:
![2017-08-27-120506_1920x1080_scrot](https://user-images.githubusercontent.com/8660255/29752261-5b07dc4a-8b20-11e7-9f5f-895755f3d7ab.png)
Immediately after clicking maximize

![2017-08-27-120514_1920x1080_scrot](https://user-images.githubusercontent.com/8660255/29752262-5ce8e18a-8b20-11e7-8832-264c51a15fac.png)
Immediately after clicking minimize

**Comment by ghost** [comment]
I think this could be fixed/worked around by additionally checking `self->client->shaped`. But there are instances where the client will request rectangular corners (as above) and there's nothing we could do about that...

Also, while I was testing this I re-generated all the patches with `git format-patch` so they'll be easier to maintain and eventually submit upstream. I'd rather not have myself as the author of all of them, though, since that seems like plagiarism. What are your thoughts?

**Comment by dylanaraps** [comment]
> ...eventually submit upstream.

The upstream for Openbox is dead (*The original bugtracker is offline and the GitHub mirror has issues disabled. Also the last release of Openbox was 2015(?)*).

> I'd rather not have myself as the author of all of them, though, since that seems like plagiarism. What are your thoughts?

I agree, the author should be set to the BunsenLabs user who created the patch.
