### ISSUE TITLE
Fullscreen windows still have corners

### ISSUE THREAD

**Issue by jontyrudman** [dylanaraps/openbox-patched#8]
Thank you so much for removing corners on tint2! I seem to have noticed something a little odd though...

When I first installed this patch on my main PC, before the patch to remove rounded corners when fullscreen, rounded corners didn't show when fullscreen.
Now, I've just installed it on my laptop, and the fullscreen windows still all have corners.
Is there something I've missed?

Thanks for bundling the patches so nicely though :)

**Comment by dylanaraps** [comment]
This is already fixed in master, I just need to update the aur package.

**Comment by dylanaraps** [comment]
Done!

**Comment by jontyrudman** [comment]
Sweet, thanks dude! :)
